name: $(GITVERSION_FullSemVer)
pool:
  vmImage: 'windows-latest'
pr: none
trigger:
  batch: true
  branches:
    include:
      - master
stages:
  - template: pipelines/templates/include-build-stage.yml
  - template: pipelines/templates/include-solution-checker-stage.yml
    parameters:
      serviceConnection: 'CI Environment - <%= package %>'
  - template: pipelines/templates/include-deploy-stage.yml
    parameters:
      environment: 'ci'
      deployServiceConnection: 'CI Environment - <%= package %>'
      environmentVariableGroup: 'CI Environment - <%= package %>'