name: $(packageVersion)$(rev:.r).0
pool:
    demands:
    - msbuild
    - visualstudio
    - vstest
steps:
  - powershell: |
       $comparisonType = "CurrentCultureIgnoreCase"
       $resultArray = git show --name-only
       $solutionList = ""
   
       foreach ($_ in $resultArray)
       {
           if ($_.StartsWith("Solutions") -and $_.Contains("Extract")) 
           {
             $solutionName = $_.Split("/")[1]

             if (!$solutionList.Contains($solutionName)) 
             {
               $solutionList += $solutionName + ";"
               Write-Host "##vso[build.addbuildtag]$solutionName" 
             }
           }
       }
    displayName: 'Configure Build Orchestration'
  - task: PowerShell@2
    displayName: 'Run BuildTestProjects Cake target via bootstrapper'
    inputs:
      targetType: filePath
      filePath: ./build.ps1
      arguments: '-Target BuildTestProjects -Verbosity Quiet'
  - task: VSTest@2
    displayName: 'Test Assemblies'
    inputs:
      testAssemblyVer2: |
        **\*Tests.Unit*.dll
        !**\*TestAdapter.dll
        !**\obj\**
      codeCoverageEnabled: true
  - task: PowerShell@2
    displayName: 'Run Default Cake target via bootstrapper'
    inputs:
      targetType: filePath
      filePath: ./build.ps1
      arguments: '-Target Default -Verbosity Quiet'
    env:
      CAKE_DYNAMICS_USERNAME: $(dynamicsUsername)
      CAKE_DYNAMICS_PASSWORD: $(dynamicsPassword)
  - task: CopyFiles@2
    displayName: "Copy package to artifact staging directory"
    inputs:
      SourceFolder: Deploy/bin/Release
      TargetFolder: "$(Build.ArtifactStagingDirectory)"
    condition: succeeded()
  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: "$(Build.ArtifactStagingDirectory)"
        artifactName: "<%= package %>"
    condition: succeeded()
trigger:
  batch: true
  branches:
    include: ["master"]
  paths:
    include: [
      "Data/Configuration/*",
      "Data/Reference/*",
      "Deploy/*",
      "Solutions/*",
      "*.yml",
      "*.cake",
      "*.ps1"
      ]
variables:
  - name: solutionList
    value: ''
  - group: Cake
  - group: Package - <%= package %>
