name: $(packageVersion)$(rev:.r).0
trigger: none
steps:
  - task: PowerShell@2
    displayName: 'Run BuildTestProjects Cake target via bootstrapper'
    inputs:
      targetType: filePath
      filePath: ./build.ps1
      arguments: '-Target BuildTestProjects -Verbosity Quiet'
  - task: VSTest@2
    displayName: 'Test Assemblies'
    inputs:
      testAssemblyVer2: |
        **\*Tests.Unit*.dll
        !**\*TestAdapter.dll
        !**\obj\**
      codeCoverageEnabled: true
  - task: PowerShell@2
    displayName: 'Run Default Cake target via bootstrapper'
    inputs:
      targetType: filePath
      filePath: ./build.ps1
      arguments: '-Target Default -Verbosity Quiet'
variables:
  - group: Package - <%= package %>